Common lisp library for assembling machine instructions in various
architectures. This assembler will require use of the [[http://www.alu.org/mop/][MetaObject Protocol]]
vie the portability library [[http://common-lisp.net/project/closer/][Closer MOP]].

Current status is somewhere between *non existant and pre-alpha*. Please do
not use this library with the expectation of it /working/.

* Setup
  This library is currently _not_ asdf installable. You need to clone this
  repository:
  : git clone git://github.com/nixeagle/nass.git
  and symlink nass.asd to some directory known to asdf-install. For
  example:
  : ln -s /location/known/to/asdf/ nass/nass.asd

  Read on for the remaining non asdf-installable dependencies. There are
  quite a few. With time these will become direct submodules for
  development ease.

*** Non asdf-installable dependencies
    Nass depends on [[http://github.com/adlai/Eos][Eos]], [[http://github.com/nixeagle/nutils][nutils]], and [[http://github.com/nixeagle/binary-data][binary-data]].

    The remaining two dependencies installation instructions are described
    at [[http://github.com/nixeagle/binary-data][binary-data]]. To avoid duplication of instructions, please read the
    readme file on that repository.

* Credits
  Thanks to martin brandenburg for collaborating on this with me.

  Thanks to [[http://common-lisp.net/project/movitz/][movitz]] for providing examples and ideas. A copy of movitz
  license can be found in [[file:COPYING-MOVITZ]]. There is little to no code
  that is directly copied from the project, but some ideas for
  implementation of this assembler. If and when code is directly copied, a
  note as to its source will be attached in a comment containing the name
  movitz.

  Thanks to [[http://www.sbcl.org/][sbcl]] and lisp for existing, its an awesome combo!
